### ISSUE TITLE
Deadline calculation wrong?

### ISSUE THREAD

**Issue by rooie1971** [spebern/goburst#2]
When i run the burstpool as described here i get some warnings, and every deadline i submit is calculated different then the miner does. What could be the cause of this, and what to do to get rid of the warnings?

make build
make[1]: Entering directory '/home/richard/goburstpool'
git submodule update --init --recursive
cd src/goburst/burstmath/libs; \
gcc  -fPIC -Wall -m64 -O3 -mtune=native  -c -o shabal64.o shabal64.s; \
gcc  -fPIC -Wall -m64 -O3 -mtune=native  -c -o mshabal_sse4.o mshabal_sse4.c; \
gcc  -fPIC -Wall -m64 -O3 -mtune=native  -mavx2 -c -o mshabal256_avx2.o mshabal256_avx2.c; \
gcc  -fPIC -Wall -m64 -O3 -mtune=native  -shared -o libburstmath.a burstmath.c shabal64.o mshabal_sse4.o mshabal256_avx2.o -lpthread -std=gnu99;
burstmath.c: In function 'calculate_deadline':
burstmath.c:96:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   req->deadline = *(uint64_t *)finals2 / req->base_target;
   ^
burstmath.c: In function 'calculate_deadlines_sse4':
burstmath.c:154:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     reqs[i]->deadline = *(uint64_t *)finals2[i] / reqs[i]->base_target;
     ^
burstmath.c: In function 'calculate_deadlines_avx2':
burstmath.c:224:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     reqs[i]->deadline = *(uint64_t *)finals2[i] / reqs[i]->base_target;;
     ^
make[1]: Leaving directory '/home/richard/goburstpool'
./goburstpool
{"level":"info","ts":1528141884.7235026,"caller":"config/config.go:194","msg":"Using default 5s for Cfg.WalletTimeout"}
{"level":"info","ts":1528141905.776647,"caller":"pool/pool.go:175","msg":"got new Block with height","height":497839}

**Comment by spebern** [comment]
Hey,

There might have been some issues with PoC1 and PoC2. I will soon have
a release of the pool that gets rid of all PoC1. 

In the meantime if you have problems with different deadlines check the following:

1. Does your miner support PoC2? (newest creepminer and blago fork used in qbundle)
2. Did you set the config option *PoC2StartHeight* correctly to 502000?
3. Are you using the 1.0 release of the pool or the master branch?

All the best,
bold

**Comment by spebern** [comment]
I don't think that there is anything wrong with
the deadline calculations, otherwise errors would occur all over
the pool network.
